### ISSUE TITLE
where can I download the original results(or source code) of SINT

### ISSUE THREAD

**Issue by Jiangfeng-Xiong** [foolwood/benchmark_results#4]
I wonder where do you get results of recent trackers. For example, I can not even get access to the source code of [SINT](https://staff.fnwi.uva.nl/r.tao/projects/SINT/SINT_proj.html). Do you get the results by running the source code or just download the results from somewhere.  whatever, can you give the original URL for the source code or results, thank you!

**Comment by foolwood** [comment]
I build this project for easily camparing with state-of-art trackers.  Each of tracking results I drawn come from the author's homepage (in order to ensure consistent with the results of the paper). In principle, I choose to believe the authors. Similar to the VOT, I'll verify the results of the paper. Trackers marked with * mean been verified.

The homepage of SINT author.(https://staff.fnwi.uva.nl/r.tao/index.html)

If you need the code, you can contact authors of SINT.
